# Generated by Django 5.2.16 on 2026-08-13 08:33

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=180, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='الرابط')),
                ('title', models.CharField(max_length=180, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشورة')),
            ],
            options={
                'verbose_name': 'صفحة محتوى',
                'verbose_name_plural': 'صفحات المحتوى',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SocialGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('image', models.ImageField(upload_to='gallery/', validators=[core.validators.validate_image_upload], verbose_name='الصورة')),
                ('alt_text', models.CharField(max_length=180, verbose_name='النص البديل')),
                ('link', models.URLField(blank=True, verbose_name='الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'صورة اجتماعية',
                'verbose_name_plural': 'المعرض الاجتماعي',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('store_name', models.CharField(default='لُمعة', max_length=120, verbose_name='اسم المتجر')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', validators=[core.validators.validate_image_upload], verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', validators=[core.validators.validate_image_upload], verbose_name='أيقونة الموقع')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='إنستجرام')),
                ('tiktok', models.URLField(blank=True, verbose_name='تيك توك')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='عنوان المتجر')),
                ('instapay_account_name', models.CharField(blank=True, max_length=120, verbose_name='اسم حساب InstaPay')),
                ('instapay_address', models.CharField(blank=True, max_length=120, verbose_name='رقم أو عنوان InstaPay')),
                ('currency', models.CharField(default='ج.م', max_length=12, verbose_name='العملة')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حد الشحن المجاني')),
                ('header_announcement', models.CharField(default='شحن مجاني للطلبات المختارة', max_length=255, verbose_name='الإعلان العلوي')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='إظهار زر واتساب')),
                ('whatsapp_message', models.CharField(default='مرحبًا، أريد الاستفسار عن منتجاتكم', max_length=255, verbose_name='رسالة واتساب الافتراضية')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('position', models.CharField(choices=[('hero', 'الرئيسي'), ('promo', 'ترويجي')], max_length=20, verbose_name='الموضع')),
                ('title', models.CharField(max_length=180, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='النص')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='نص الزر')),
                ('button_url', models.CharField(default='/products/', max_length=255, verbose_name='رابط الزر')),
                ('image', models.ImageField(upload_to='banners/', validators=[core.validators.validate_image_upload], verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active', 'order'], name='core_banner_positio_6b58ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الخطوة')),
                ('description', models.CharField(blank=True, max_length=180, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, upload_to='routine/', validators=[core.validators.validate_image_upload], verbose_name='الصورة')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='التصنيف')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'خطوة روتين',
                'verbose_name_plural': 'روتين العناية',
                'ordering': ['order'],
            },
        ),
    ]
