# Generated by Django 5.2.16 on 2026-08-16 06:42

from django.db import migrations, models


def create_default_offer(apps, schema_editor):
    Offer = apps.get_model('core', 'Offer')
    Product = apps.get_model('products', 'Product')
    discounted_products = Product.objects.filter(
        is_active=True,
        category__is_active=True,
        old_price__isnull=False,
    )
    if discounted_products.exists():
        offer = Offer.objects.create(
            eyebrow='وقت التدليل',
            title='عروض لا تفوتك',
            subtitle='منتجات مختارة بأسعار أخف لفترة محدودة.',
            button_text='كل العروض',
            is_active=True,
        )
        offer.products.set(discounted_products)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('eyebrow', models.CharField(default='وقت التدليل', max_length=80, verbose_name='النص الصغير')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان العرض')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='وصف العرض')),
                ('button_text', models.CharField(default='كل العروض', max_length=60, verbose_name='نص زر كل العروض')),
                ('button_url', models.CharField(blank=True, help_text='اتركيه فارغًا لعرض منتجات هذا العرض تلقائيًا.', max_length=255, verbose_name='رابط مخصص للزر')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية العرض')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('products', models.ManyToManyField(related_name='offer_campaigns', to='products.product', verbose_name='المنتجات')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order', 'starts_at', 'ends_at'], name='core_offer_is_acti_1aadf3_idx')],
            },
        ),
        migrations.RunPython(create_default_offer, migrations.RunPython.noop),
    ]
