# Generated by Django 5.2.16 on 2026-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='instapay_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل الدفع عبر InstaPay'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='inventory_reservation_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='مدة حجز المخزون (دقيقة)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='return_window_days',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='مدة طلب الإرجاع (يوم)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='terms_version',
            field=models.CharField(default='1.0', max_length=30, verbose_name='نسخة الشروط'),
        ),
    ]
