# Generated by Django 5.2.16 on 2026-08-25 08:42

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_legacy_seed_copy'),
        ('products', '0005_product_is_bundle_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bundle_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اختياري؛ عند تركه فارغًا يُستخدم مجموع أسعار المنتجات.', max_digits=10, null=True, verbose_name='السعر قبل العرض'),
        ),
        migrations.AddField(
            model_name='offer',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض كاملًا'),
        ),
        migrations.AddField(
            model_name='offer',
            name='bundle_product',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bundle_offer', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='offers/', validators=[core.validators.validate_image_upload], verbose_name='صورة العرض'),
        ),
        migrations.AddField(
            model_name='offer',
            name='sell_as_bundle',
            field=models.BooleanField(default=False, help_text='يفتح العرض كمنتج واحد ويُضاف إلى السلة بضغطة واحدة.', verbose_name='بيع العرض كباقة واحدة'),
        ),
    ]
