# Generated by Django 5.2.16 on 2026-08-29 08:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_offer_bundle_old_price_offer_bundle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[core.validators.validate_image_upload], verbose_name='صورة الموبايل'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[core.validators.validate_image_upload], verbose_name='صورة التابلت'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[core.validators.validate_image_upload], verbose_name='الصورة (شاشات كبيرة)'),
        ),
    ]
