# Generated by Django 5.2.16 on 2026-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banner_image_mobile_banner_image_tablet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='back_in_stock_emails_enabled',
            field=models.BooleanField(default=True, verbose_name='إرسال تنبيهات عودة المنتجات للمخزون'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='customer_order_emails_enabled',
            field=models.BooleanField(default=True, verbose_name='إرسال تحديثات الطلب بالبريد للعميل'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='مثال: G-XXXXXXXXXX', max_length=32, verbose_name='معرّف Google Analytics 4'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='المعرّف الرقمي من Meta Events Manager.', max_length=32, verbose_name='معرّف Meta Pixel'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, help_text='المعرّف من TikTok Events Manager.', max_length=32, verbose_name='معرّف TikTok Pixel'),
        ),
    ]
