# Generated by Django 5.2.16 on 2026-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='normalized_phone',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف الموحد'),
        ),
    ]
