# Generated by Django 5.2.16 on 2026-08-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_normalized_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('export_customer_data', 'Can export customer data')], 'verbose_name': 'ملف عميل', 'verbose_name_plural': 'ملفات العملاء'},
        ),
    ]
