# Generated by Django 5.2.16 on 2026-08-13 08:33

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='المحافظة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تكلفة الشحن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'منطقة شحن',
                'verbose_name_plural': 'مناطق الشحن',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], max_length=20, verbose_name='نوع الخصم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قيمة الخصم')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'كوبونات الخصم',
                'indexes': [models.Index(fields=['code', 'is_active'], name='orders_coup_code_3a9c8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='رقم الطلب')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم بالكامل')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم الهاتف')),
                ('alternative_phone', models.CharField(blank=True, max_length=30, verbose_name='رقم إضافي')),
                ('city', models.CharField(max_length=120, verbose_name='المدينة / المنطقة')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان بالتفصيل')),
                ('landmark', models.CharField(blank=True, max_length=180, verbose_name='علامة مميزة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطلب')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='المجموع الفرعي')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='الخصم')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='الشحن')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='الإجمالي')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'الدفع عند الاستلام'), ('instapay', 'تحويل InstaPay')], max_length=30, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('unpaid', 'الدفع عند الاستلام'), ('pending_verification', 'في انتظار مراجعة التحويل'), ('verified', 'تم تأكيد الدفع'), ('rejected', 'تم رفض إثبات الدفع')], max_length=30, verbose_name='حالة الدفع')),
                ('payment_receipt', models.ImageField(blank=True, upload_to='payment_receipts/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='إثبات التحويل')),
                ('payment_note', models.TextField(blank=True, verbose_name='ملاحظة مراجعة الدفع')),
                ('status', models.CharField(choices=[('new', 'طلب جديد'), ('confirmed', 'تم التأكيد'), ('preparing', 'جاري التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], db_index=True, default='new', max_length=20, verbose_name='حالة الطلب')),
                ('stock_released', models.BooleanField(default=False, editable=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon', verbose_name='الكوبون')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.shippingzone', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='اسم المنتج')),
                ('sku', models.CharField(max_length=60, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='الإجمالي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', 'status'], name='orders_orde_created_4a9c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
    ]
