# Generated by Django 5.2.16 on 2026-08-16 07:50

import core.storage
import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_coupon_minimum_order_and_more'),
        ('products', '0003_inventorybatch_productvariant_variantoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer_key', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('reserved', 'محجوز'), ('consumed', 'مستخدم'), ('released', 'محرر')], db_index=True, default='reserved', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('reserved_until', models.DateTimeField(db_index=True, verbose_name='محجوز حتى')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('consumed', 'تم الخصم'), ('released', 'تم التحرير'), ('expired', 'منتهي')], db_index=True, default='active', max_length=16, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'حجز مخزون',
                'verbose_name_plural': 'حجوزات المخزون',
            },
        ),
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('reason', models.CharField(max_length=180, verbose_name='سبب الإرجاع')),
                ('customer_note', models.TextField(blank=True, verbose_name='تفاصيل العميل')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('status', models.CharField(choices=[('requested', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('received', 'تم استلام المرتجع'), ('refunded', 'تم رد المبلغ')], db_index=True, default='requested', max_length=16, verbose_name='الحالة')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='المبلغ المسترد')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('restockable', models.BooleanField(default=False, verbose_name='صالح للإعادة إلى المخزون')),
                ('restocked', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.category', verbose_name='تصنيفات محددة'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_customer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام لكل عميل'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product', verbose_name='منتجات محددة'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_consumed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='مفتاح عدم التكرار'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='المبلغ المسترد'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='انتهاء حجز المخزون'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_counted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة على الشروط'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='نسخة الشروط'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='إجمالي التكلفة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='الخيار'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=220, verbose_name='وصف الخيار'),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='estimated_delivery_max_days',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='أقصى مدة للتوصيل'),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='estimated_delivery_min_days',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='أقل مدة للتوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to='payment_receipts/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='إثبات التحويل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'الدفع عند الاستلام'), ('pending_verification', 'في انتظار مراجعة التحويل'), ('verified', 'تم تأكيد الدفع'), ('rejected', 'تم رفض إثبات الدفع'), ('refunded', 'تم رد المبلغ')], max_length=30, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'طلب جديد'), ('awaiting_payment', 'في انتظار الدفع'), ('confirmed', 'تم التأكيد'), ('preparing', 'جاري التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('payment_failed', 'فشل الدفع'), ('refunded', 'مسترد')], db_index=True, default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='order_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('total'))), name='order_refund_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='order_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='order_item_total_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shippingzone',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_delivery_max_days__gte', models.F('estimated_delivery_min_days'))), name='shipping_delivery_days_ordered'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.productvariant', verbose_name='الخيار'),
        ),
        migrations.AddField(
            model_name='orderauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='reservationbatchallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='products.inventorybatch'),
        ),
        migrations.AddField(
            model_name='reservationbatchallocation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='orders.inventoryreservation'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'customer_key', 'status'], name='orders_coup_coupon__957844_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['status', 'reserved_until'], name='orders_inve_status_831c15_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'variant'), name='unique_order_stock_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservationbatchallocation',
            constraint=models.UniqueConstraint(fields=('reservation', 'batch'), name='unique_reservation_batch'),
        ),
        migrations.AddConstraint(
            model_name='reservationbatchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='return_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.UniqueConstraint(fields=('return_request', 'order_item'), name='unique_return_order_item'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_item_quantity_positive'),
        ),
    ]
