# Generated by Django 5.2.16 on 2026-08-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('transition_order', 'Can transition order status'), ('verify_payment', 'Can verify order payment'), ('view_payment_receipt', 'Can view private payment receipt'), ('view_financial_reports', 'Can view financial reports')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
    ]
