# Generated by Django 5.2.16 on 2026-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
        ('products', '0004_remove_inventorybatch_unique_inventory_batch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryreservation',
            name='unique_order_stock_reservation',
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('order', 'product', 'variant'), name='unique_order_variant_reservation'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('order', 'product'), name='unique_order_product_reservation'),
        ),
    ]
