# Generated by Django 5.2.16 on 2026-08-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_inventoryreservation_unique_order_stock_reservation_and_more'),
        ('products', '0005_product_is_bundle_bundleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemBundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='اسم مكوّن الباقة')),
                ('variant_name', models.CharField(blank=True, max_length=220, verbose_name='وصف الخيار')),
                ('sku', models.CharField(max_length=60, verbose_name='SKU')),
                ('quantity_per_bundle', models.PositiveSmallIntegerField(verbose_name='الكمية في الباقة')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='orders.orderitem')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bundle_component_snapshots', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bundle_component_snapshots', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'مكوّن باقة في الطلب',
                'verbose_name_plural': 'مكوّنات الباقات في الطلب',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_per_bundle__gt', 0)), name='order_bundle_component_quantity_positive')],
            },
        ),
    ]
