# Generated by Django 5.2.16 on 2026-08-13 08:33

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='الرابط')),
                ('image', models.ImageField(blank=True, upload_to='categories/', validators=[core.validators.validate_image_upload], verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='products_ca_is_acti_65c3de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=180, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=210, unique=True, verbose_name='الرابط')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ingredients', models.TextField(blank=True, verbose_name='المكونات')),
                ('usage', models.TextField(blank=True, verbose_name='طريقة الاستخدام')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر القديم')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='المخزون')),
                ('main_image', models.ImageField(blank=True, upload_to='products/', validators=[core.validators.validate_image_upload], verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='الأكثر مبيعًا')),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('sales_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد المبيعات')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('image', models.ImageField(upload_to='products/gallery/', validators=[core.validators.validate_image_upload], verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='النص البديل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_seller', '-sales_count'], name='products_pr_is_best_d3b906_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
    ]
