# Generated by Django 5.2.16 on 2026-08-16 07:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('batch_number', models.CharField(max_length=80, verbose_name='رقم التشغيلة')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, editable=False, verbose_name='الكمية المحجوزة')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنتاج')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'تشغيلة مخزون',
                'verbose_name_plural': 'تشغيلات المخزون',
                'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True), 'received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('option_summary', models.CharField(max_length=220, verbose_name='وصف الخيار')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='اتركه فارغًا لاستخدام سعر المنتج.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الخيار')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='السعر القديم')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='المخزون')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, editable=False, verbose_name='الكمية المحجوزة')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='الباركود')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (جرام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خيار منتج',
                'verbose_name_plural': 'خيارات المنتجات',
                'ordering': ['product', 'option_summary'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('option_type', models.CharField(choices=[('size', 'الحجم'), ('scent', 'الرائحة'), ('concentration', 'التركيز'), ('spf', 'درجة الحماية SPF'), ('formula', 'التركيبة')], max_length=24, verbose_name='نوع الخيار')),
                ('value', models.CharField(max_length=100, verbose_name='القيمة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خيار منتج',
                'verbose_name_plural': 'خيارات المنتجات',
                'ordering': ['option_type', 'order', 'value'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='الفوائد'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='العلامة التجارية'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=120, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='product',
            name='cruelty_free',
            field=models.BooleanField(blank=True, null=True, verbose_name='غير مجرب على الحيوانات'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_types',
            field=models.CharField(blank=True, max_length=255, verbose_name='أنواع الشعر'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='له خيارات'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_ingredients',
            field=models.TextField(blank=True, verbose_name='المكونات الفعالة'),
        ),
        migrations.AddField(
            model_name='product',
            name='pao_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الصلاحية بعد الفتح (شهر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='الكمية المحجوزة'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='الحجم'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.CharField(blank=True, max_length=255, verbose_name='أنواع البشرة'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=255, verbose_name='مناسب لـ'),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan',
            field=models.BooleanField(blank=True, null=True, verbose_name='نباتي'),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, verbose_name='التحذيرات'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='product_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('stock_quantity'))), name='product_reserved_lte_stock'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.productvariant', verbose_name='الخيار'),
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(fields=('option_type', 'value'), name='unique_variant_option_value'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='variants', to='products.variantoption', verbose_name='الخيارات'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['product', 'variant', 'is_active', 'expiry_date'], name='products_in_product_27fba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'batch_number'), name='unique_inventory_batch'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batch_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='batch_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='batch_reserved_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0)), name='batch_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='variant_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='variant_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('stock_quantity'))), name='variant_reserved_lte_stock'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('old_price__isnull', True), ('price__isnull', True), ('old_price__gt', models.F('price')), _connector='OR'), name='variant_old_price_gt_price'),
        ),
    ]
