# Generated by Django 5.2.16 on 2026-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventorybatch_productvariant_variantoption_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorybatch',
            name='unique_inventory_batch',
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('product', 'variant', 'batch_number'), name='unique_variant_inventory_batch'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('product', 'batch_number'), name='unique_product_inventory_batch'),
        ),
    ]
