# Generated by Django 5.2.16 on 2026-08-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_inventorybatch_unique_inventory_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='الباقة تُباع كمنتج واحد ويُخصم مخزون مكوّناتها تلقائيًا.', verbose_name='باقة / بوكس'),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='الكمية داخل الباقة')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product', verbose_name='الباقة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='products.product', verbose_name='المنتج داخل الباقة')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='products.productvariant', verbose_name='الخيار')),
            ],
            options={
                'verbose_name': 'مكوّن باقة',
                'verbose_name_plural': 'مكوّنات الباقات',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bundle_item_quantity_positive'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('bundle', 'product', 'variant'), name='unique_bundle_variant_item'), models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('bundle', 'product'), name='unique_bundle_product_item')],
            },
        ),
    ]
