# Generated by Django 5.2.16 on 2026-08-25 09:50

import django.db.models.deletion
from django.db import migrations, models


def copy_primary_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    through = Product.categories.through
    through.objects.bulk_create([
        through(product_id=product_id, category_id=category_id)
        for product_id, category_id in Product.objects.values_list('id', 'category_id')
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_bundle_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='يمكن عرض المنتج داخل أكثر من قسم.', related_name='products_in_section', to='products.category', verbose_name='الأقسام'),
        ),
        migrations.RunPython(copy_primary_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='القسم الأساسي'),
        ),
    ]
