# Generated by Django 5.2.16 on 2026-08-25 12:02

import django.db.models.deletion
from django.db import migrations, models


def detach_offer_products_from_categories(apps, schema_editor):
    Offer = apps.get_model('core', 'Offer')
    Product = apps.get_model('products', 'Product')
    bundle_ids = list(
        Offer.objects.filter(
            sell_as_bundle=True,
            bundle_product_id__isnull=False,
        ).values_list('bundle_product_id', flat=True)
    )
    if not bundle_ids:
        return
    Product.objects.filter(pk__in=bundle_ids).update(category_id=None)
    Product.categories.through.objects.filter(product_id__in=bundle_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_offer_bundle_old_price_offer_bundle_price_and_more'),
        ('products', '0006_product_multiple_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='يمكن عرض المنتج داخل أكثر من قسم.', related_name='products_in_section', to='products.category', verbose_name='الأقسام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='القسم الأساسي'),
        ),
        migrations.RunPython(detach_offer_products_from_categories, migrations.RunPython.noop),
    ]
