# Generated by Django 5.2.16 on 2026-08-29 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offer_products_without_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='بانتظار التنبيه')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال التنبيه')),
                ('product_url', models.URLField(blank=True, max_length=500, verbose_name='رابط المنتج')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_subscriptions', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'اشتراك عودة للمخزون',
                'verbose_name_plural': 'اشتراكات العودة للمخزون',
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_ba_product_d743fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'email'), name='unique_product_stock_subscription')],
            },
        ),
    ]
